spring:
  application:
    name: instagram-poster
server:
  port: 9000

groq:
  api:
    base-url: https://api.groq.com/openai/v1
    key: ${GROQ_API_KEY}
    model:  ${GROQ_MODEL:llama-3.1-8b-instant}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

instagram:
  access-token: ${INSTAGRAM_ACCESS_TOKEN}
  business-id: ${INSTAGRAM_BUSINESS_ID}

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: health