spring:
  application-name: instagram-poster
server:
  port: 9000

groq:
  api:
    base-url: https://api.groq.com/openai/v1
    key: {API_Key}
    model: {Model}
app:
  image:
    input-dir: ./images/input
    processed-dir: ./images/processed
    supported-formats: jpg,jpeg,png

cloudinary:
  cloud-name: {Cloud_Name }
  api-key: {App_Key}
  api-secret: {API_Secret}


instagram:
  access-token: {Access_Token}
  business-id: {Business_ID}
